# TCL File Generated by Component Editor 18.1
# Sun Oct 28 14:51:14 CET 2018
# DO NOT MODIFY


# 
# LcdCtrl "LcdCtrl" v18.1
#  2018.10.28.14:51:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LcdCtrl
# 
set_module_property DESCRIPTION ""
set_module_property NAME LcdCtrl
set_module_property VERSION 18.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME LcdCtrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ctrl_lcd_avalonSlave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ctrl_lcd_avalonSlave.vhdl VHDL PATH ctrl_lcd_avalonSlave.vhdl TOP_LEVEL_FILE
add_fileset_file SendReceiveInterface.vhdl VHDL PATH SendReceiveInterface.vhdl


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset Reset reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock Clock clk Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave slave_cs chipselect Input 1
add_interface_port avalon_slave slave_we write Input 1
add_interface_port avalon_slave slave_rd read Input 1
add_interface_port avalon_slave slave_write_data writedata Input 32
add_interface_port avalon_slave slave_read_data readdata Output 32
add_interface_port avalon_slave slave_wait_request waitrequest Output 1
add_interface_port avalon_slave slave_address address Input 2
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point lcd_ctrl_wire
# 
add_interface lcd_ctrl_wire conduit end
set_interface_property lcd_ctrl_wire associatedClock clock
set_interface_property lcd_ctrl_wire associatedReset reset
set_interface_property lcd_ctrl_wire ENABLED true
set_interface_property lcd_ctrl_wire EXPORT_OF ""
set_interface_property lcd_ctrl_wire PORT_NAME_MAP ""
set_interface_property lcd_ctrl_wire CMSIS_SVD_VARIABLES ""
set_interface_property lcd_ctrl_wire SVD_ADDRESS_GROUP ""

add_interface_port lcd_ctrl_wire DataBus databus Bidir 16
add_interface_port lcd_ctrl_wire ChipSelectBar chipselectbar Output 1
add_interface_port lcd_ctrl_wire DataCommandBar datacommandbar Output 1
add_interface_port lcd_ctrl_wire IM0 im0 Output 1
add_interface_port lcd_ctrl_wire ReadBar readbar Output 1
add_interface_port lcd_ctrl_wire ResetBar resetbar Output 1
add_interface_port lcd_ctrl_wire WriteBar writebar Output 1

